import java.util.Locale
import java.util.Base64
import groovy.json.JsonSlurper
import groovy.json.JsonOutput
import java.security.MessageDigest

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.android.lint)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.jetbrains.compose)

    id("androidx.room")
    id("com.google.devtools.ksp")
    alias(libs.plugins.sentry.kotlin.multiplatform)

}

compose.resources {
    publicResClass = true
    generateResClass = always
}

// Generates SupportedLanguages.kt from the Weblate-managed locale folders in
// composeResources, so merging a translation PR is the only step needed to
// register a new language (picker entries, tags and native display names).
val supportedLanguagesDir = layout.buildDirectory.dir("generated/supportedLanguages/kotlin")
val generateSupportedLanguages = tasks.register("generateSupportedLanguages") {
    val resDir = layout.projectDirectory.dir("src/commonMain/composeResources").asFile
    val localeFolders = providers.provider {
        resDir.listFiles { file: File -> file.isDirectory }.orEmpty()
            .map { it.name }
            .filter { it == "values" || it.startsWith("values-") }
            .sorted()
    }
    inputs.property("localeFolders", localeFolders)
    outputs.dir(supportedLanguagesDir)
    doLast {
        // Android resource qualifier -> BCP-47 tag; the bare "values" folder is
        // the development language, English.
        fun folderToTag(folder: String): String? {
            if (folder == "values") return "en"
            val qualifier = folder.removePrefix("values-")
            if (qualifier.startsWith("b+")) return qualifier.removePrefix("b+").replace('+', '-')
            val parts = qualifier.split("-r", limit = 2)
            val language = when (val lang = parts[0]) {
                // Android resource folders use the legacy ISO codes; BCP-47 doesn't.
                "in" -> "id"
                "iw" -> "he"
                "ji" -> "yi"
                else -> lang
            }
            // Skip non-locale qualifiers (theme, density, ...)
            if (!language.matches(Regex("[a-z]{2,3}"))) return null
            return if (parts.size == 2) "$language-${parts[1]}" else language
        }

        // The language's own name for itself, from the JDK's CLDR data.
        fun displayName(tag: String): String {
            val locale = Locale.forLanguageTag(tag)
            val name = locale.getDisplayLanguage(locale).ifBlank { tag }
            return name.replaceFirstChar { if (it.isLowerCase()) it.titlecase(locale) else it.toString() }
        }

        val tags = localeFolders.get().mapNotNull(::folderToTag).distinct()
            .sortedWith(compareBy({ it != "en" }, { it }))
        val entries = tags.joinToString("\n") { tag ->
            "        AppLanguage(tag = \"$tag\", displayName = \"${displayName(tag)}\"),"
        }
        val file = supportedLanguagesDir.get()
            .file("com/sasch/cameragps/sharednew/language/SupportedLanguages.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// GENERATED by :sharednew:generateSupportedLanguages — do not edit.
            |// Derived from the src/commonMain/composeResources/values-* folders, so a
            |// merged Weblate language lands here (and in the in-app picker) automatically.
            |package com.sasch.cameragps.sharednew.language
            |
            |object SupportedLanguages {
            |    val entries: List<AppLanguage> = listOf(
            |$entries
            |    )
            |
            |    fun fromTag(tag: String): AppLanguage? {
            |        val normalized = tag.substringBefore('-').lowercase()
            |        return entries.firstOrNull { it.tag.substringBefore('-').lowercase() == normalized }
            |    }
            |}
            |""".trimMargin()
        )
    }
}


// --- Sentry Cocoa linking (Apple targets only) --------------------------------
//
// The plugin adds the `-F` search path for the Sentry Cocoa xcframework that
// Xcode's Swift Package Manager checked out for iosApp/alphagps.xcodeproj
// (product `Sentry-Dynamic`); the published cinterop klib already carries the
// matching `-framework Sentry`.
//
// **The foss guarantee lives here.** Left at its default, the plugin injects
// `api("io.sentry:sentry-kotlin-multiplatform")` into commonMain, which would
// put the Sentry Java SDK into :sharednew's Android artifact and therefore into
// the F-Droid flavor of :app. Turning auto-install off reduces the plugin to
// pure Apple-target linking; the dependency stays declared by hand in the
// iosMain source set below. Do not remove this.
//
// Beyond that the plugin is inert for Android work: it only configures Apple
// binaries, only on a Mac host, and only when an Apple compile task is actually
// in the requested task graph.
sentryKmp {
    autoInstall.enabled.set(false)

    // Without this the plugin file-walks the repo root looking for a .xcodeproj,
    // which here means walking website/node_modules (138 MB).
    linker.xcodeprojPath.set(rootProject.layout.projectDirectory.dir("iosApp/alphagps.xcodeproj").asFile.absolutePath)
    // Escape hatch for a checkout that has never been opened in Xcode:
    // -Psentry.cocoa.frameworkPath=/path/to/Sentry-Dynamic.xcframework
    linker.frameworkPath.set(providers.gradleProperty("sentry.cocoa.frameworkPath"))
}

val heifTestFixturesDir = layout.buildDirectory.dir("generated/heifTestFixtures/kotlin")
// Opt-in originals stay outside the repository and are packaged only in the test APK.
val sonyImageFixtures = providers.gradleProperty("sonyImageFixtures").map { rootProject.file(it) }
val sonyImageFixtureSources = layout.buildDirectory.dir("generated/sonyImageFixtures/kotlin")
val generateSonyImageFixtures = tasks.register("generateSonyImageFixtures") {
    inputs.dir(sonyImageFixtures)
    outputs.dir(sonyImageFixtureSources)
    doLast {
        val directory = sonyImageFixtures.get().canonicalFile
        val manifest = JsonSlurper().parse(directory.resolve("manifest.json")) as Map<*, *>
        val fixtures = manifest["fixtures"] as List<*>
        require(fixtures.isNotEmpty()) { "Sony image manifest contains no fixtures" }
        fun literal(value: Any?) = JsonOutput.toJson(value).replace("$", "\\$")
        val entries = fixtures.map { entry ->
            val fixture = entry as Map<*, *>
            val name = fixture["file"] as String
            require(
                File(name).name == name && name !in listOf(
                    ".",
                    ".."
                )
            ) { "Use a plain fixture filename: $name" }
            val file = directory.resolve(name)
            require(file.isFile && file.canonicalFile.parentFile == directory) { "Missing fixture: $name" }
            val digest = MessageDigest.getInstance("SHA-256")
            file.inputStream().use { input ->
                val buffer = ByteArray(65536)
                var count = input.read(buffer)
                while (count != -1) {
                    digest.update(buffer, 0, count)
                    count = input.read(buffer)
                }
            }
            val hash = digest.digest().joinToString("") { "%02x".format(it) }
            require(hash == fixture["sha256"]) { "Fixture checksum changed: $name" }
            val width = (fixture["width"] as Number).toInt()
            val height = (fixture["height"] as Number).toInt()
            val orientation = (fixture["orientation"] as Number).toInt()
            require(width > 0 && height > 0 && orientation in 1..8) { "Invalid dimensions/orientation: $name" }
            val format = fixture["format"] as String
            require(format in listOf("heif", "jpeg")) { "Unsupported fixture format: $format" }
            val metadata = fixture["metadata"] as Map<*, *>
            require(metadata["make"] == "SONY" && !(metadata["model"] as? String).isNullOrBlank()) { "Expected Sony camera metadata: $name" }
            require(metadata.keys.all {
                it in setOf(
                    "make",
                    "model",
                    "lensModel",
                    "dateTimeOriginal",
                    "iso"
                )
            }) { "Unsupported metadata key: $name" }
            val bitDepth = (fixture["bitDepth"] as? Number)?.toInt() ?: 0
            val chroma = (fixture["chroma"] as? Number)?.toInt() ?: 0
            require(
                format != "heif" || (bitDepth in 8..16 && chroma in listOf(
                    420,
                    422,
                    444
                ))
            ) { "HEIF fixtures need bitDepth and chroma: $name" }
            val tags =
                metadata.entries.joinToString { "${literal(it.key)} to ${literal(it.value as String)}" }
            "SonyImageFixture(${literal(name)}, ${literal(format)}, $width, $height, $orientation, mapOf($tags), $bitDepth, $chroma)"
        }.joinToString(",\n        ")
        val output = sonyImageFixtureSources.get()
            .file("com/sasch/cameragps/sharednew/remote/wifi/SonyImageFixtures.kt").asFile
        output.parentFile.mkdirs()
        output.writeText(
            """
            package com.sasch.cameragps.sharednew.remote.wifi
            internal object SonyImageFixtures {
                const val directory = ${literal(directory.path)}
                val all = listOf(
                    $entries
                )
            }
        """.trimIndent()
        )
    }
}

androidComponents {
    onVariants { variant ->
        variant.deviceTests.values.forEach { test ->
            test.sources.assets?.addStaticSourceDirectory("src/commonTest/resources")
        }
        if (sonyImageFixtures.isPresent) {
            variant.deviceTests.values.forEach { test ->
                test.sources.assets?.addStaticSourceDirectory(sonyImageFixtures.get().path)
            }
        }
    }
}

val generateHeifTestFixtures = tasks.register("generateHeifTestFixtures") {
    val fixtures = rootProject.layout.projectDirectory.dir("heif/src/androidTest/assets")
    val arwPrefix =
        layout.projectDirectory.file("src/commonTest/resources/sony/DSC04175-preview-prefix.bin")
    inputs.file(arwPrefix)
    inputs.files(
        fixtures.file("red-422-10bit.hif"), fixtures.file("red-422-10bit-rotated.hif"),
        fixtures.file("red-422-preview.hif")
    )
    outputs.dir(heifTestFixturesDir)
    doLast {
        val entries = mapOf(
            "original" to "red-422-10bit.hif", "rotated" to "red-422-10bit-rotated.hif",
            "preview" to "red-422-preview.hif"
        )
            .map { (name, file) ->
                val encoded = Base64.getEncoder().encodeToString(fixtures.file(file).asFile.readBytes())
                "    val $name: ByteArray get() = kotlin.io.encoding.Base64.decode(\"$encoded\")"
            }.joinToString("\n")
        val output = heifTestFixturesDir.get().file("com/sasch/cameragps/sharednew/remote/wifi/HeifTestFixtures.kt").asFile
        output.parentFile.mkdirs()
        output.writeText("package com.sasch.cameragps.sharednew.remote.wifi\n\ninternal object HeifTestFixtures {\n$entries\n}\n")
        output.appendText(
            "\ninternal object SonyArwTestFixture { const val path = ${
                JsonOutput.toJson(
                    arwPrefix.asFile.absolutePath
                ).replace("$", "\\$")
            } }\n"
        )
    }
}

kotlin {

    // Target declarations - add or remove as needed below. These define
    // which platforms this KMP module supports.
    // See: https://kotlinlang.org/docs/multiplatform-discover-project.html#targets
    android {
        androidResources.enable = true
        namespace = "com.sasch.cameragps.sharednew"
        compileSdk {
            version = release(37) {
                minorApiLevel = 1
            }
        }
        minSdk = 26

        withHostTestBuilder {
        }

        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    // For iOS targets, this is also where you should
    // configure native binary output. For more information, see:
    // https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#build-xcframeworks

    // A step-by-step guide on how to include this library in an XCode
    // project can be found here:
    // https://developer.android.com/kotlin/multiplatform/migrate
    val xcfName = "sharedKit"

    /* iosX64 {
         binaries.framework {
             baseName = xcfName
         }
     }*/

    iosArm64 {
        binaries.framework {
            baseName = xcfName
        }
    }

    iosSimulatorArm64 {
        binaries.framework {
            baseName = xcfName
        }
    }

    // Source set declarations.
    // Declaring a target automatically creates a source set with the same name. By default, the
    // Kotlin Gradle Plugin creates additional source sets that depend on each other, since it is
    // common to share sources between related targets.
    // See: https://kotlinlang.org/docs/multiplatform-hierarchy.html
    sourceSets {
        commonMain {
            kotlin.srcDir(generateSupportedLanguages)
            dependencies {
                implementation(libs.kotlin.stdlib)
                // Add KMP dependencies here
                implementation(libs.compose.runtime.multiplatform)
                implementation(libs.compose.foundation.multiplatform)
                implementation(libs.compose.material3.multiplatform)
                //     implementation(libs.components.resources)
                implementation(libs.navigationevent)

                //implementation(libs.androidx.sqlite.bundled)
                implementation(libs.androidx.room.runtime)
                implementation(libs.components.resources)
                implementation(libs.androidx.sqlite.bundled)
                implementation(libs.logging)
                implementation(libs.kotlinx.datetime)
                implementation(libs.androidx.lifecycle.viewmodel)
                implementation(libs.lifecycle.runtime.compose)


            }
        }

        commonTest {
            dependencies {
                implementation(libs.kotlin.test)
                implementation(libs.kotlinx.coroutines.test)
            }
        }

        androidMain {
            dependencies {
                // Add Android-specific dependencies here. Note that this source set depends on
                // commonMain by default and will correctly pull the Android artifacts of any KMP
                // dependencies declared in commonMain.
                // LanguagePreference.android.kt: per-app language below API 33.
                implementation(libs.androidx.appcompat)
                implementation(libs.androidx.activity.compose)
                implementation(libs.androidx.exifinterface)
                implementation(project(":heif"))

            }
        }

        getByName("androidDeviceTest") {
            dependencies {
                implementation(libs.androidx.runner)
                implementation(libs.androidx.core)
                implementation(libs.androidx.junit)
            }
        }

        iosTest {
            kotlin.srcDir(generateHeifTestFixtures)
        }

        if (sonyImageFixtures.isPresent) {
            for (target in listOf("iosTest", "androidDeviceTest")) {
                getByName(target) {
                    kotlin.srcDir("src/cameraImageTest/kotlin")
                    kotlin.srcDir("src/${target.removeSuffix("Test")}CameraImageTest/kotlin")
                    kotlin.srcDir(generateSonyImageFixtures)
                }
            }
        }

        iosMain {
            dependencies {
                // Add iOS-specific dependencies here. This a source set created by Kotlin Gradle
                // Plugin (KGP) that each specific iOS target (e.g., iosX64) depends on as
                // part of KMP’s default source set hierarchy. Note that this source set depends
                // on common by default and will correctly pull the iOS artifacts of any
                // KMP dependencies declared in commonMain.

                // Sentry stays in iosMain: moving it to commonMain would drag the
                // Sentry Java SDK into :sharednew's Android artifact and therefore
                // into the foss (F-Droid) flavor of :app, which must stay free of
                // proprietary dependencies.
                implementation(libs.sentry.kotlin.multiplatform)
            }
        }
    }

}

dependencies {
    add("kspAndroid", libs.androidx.room.compiler)
    add("kspIosSimulatorArm64", libs.androidx.room.compiler)
    add("kspIosArm64", libs.androidx.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}
